### ISSUE TITLE
[FEATURE] Retrieve credentials from environment variables

### ISSUE THREAD

**Issue by instinet-lewis-boon** [sonatype-nexus-community/scan-gradle-plugin#21]
* **What are you trying to do?**

The [Nexus IQ for Gitlab CI](https://help.sonatype.com/integrations/nexus-and-continuous-integration/nexus-iq-for-gitlab-ci) documentation suggests storing the Nexus IQ credentials as environment variables when using the Docker image. I would like this plugin to also use these credentials if available.

* **What feature or behavior is this required for?**

By also using the same environment variables we can simplify our internal documentation as build managers can standardise the setup for scans using the Docker image and this Gradle plugin. Gitlab CI also supports setting variables at the group level. This would allow us to store the credentials once for a team's projects.

* **How could we solve this issue? (Not knowing is okay!)**

We're solving this by setting the following config:

```
nexusIQScan {
    username = System.getenv('NEXUS_IQ_USERNAME')
    password = System.getenv('NEXUS_IQ_PASSWORD')
    serverUrl = 'https://nexusiq.example.com'
    applicationId = 'MyAppId'
}
```

I'd like to omit this boilerplate and the plugin should try to get the credentials from `NEXUS_IQ_USERNAME` and `NEXUS_IQ_PASSWORD`. We could then improve the error messages.

* **Anything else?**

I'm really happy that you've created this plugin. It integrates extremely easy and setup was quick and painless. **But**, I spent more time trying to find it than setting it up. 

I started on [this page](https://help.sonatype.com/integrations/nexus-iq-cli#NexusIQCLI-NexusIQCLIDockerImage). There's no mention of neither the page on how to setup Gitlab CI nor this plugin. I ended up stumbling on [the blog post](https://blog.sonatype.com/new-sonatype-scan-gradle-plugin) by searching Google.

cc @bhamail / @DarthHater / @guillermo-varela

**Comment by guillermo-varela** [comment]
Hi  @instinet-lewis-boon,

There is now a section on the `README.md` file with instructions on how to set sensitive data by using project properties or environment variables: https://github.com/sonatype-nexus-community/scan-gradle-plugin#sensitive-data

Hopefully that's clear enough so people can setup this plugin quickly :)
In addition to that, from #36, we're pending to add a link with a sample repo showing how to use this plugin in multiple CI/CD tools.

About using default environment variable names, I'm not a big fan of that idea as IQ Server allows to have multiple users with different roles across applications and although ideally each project should apply and run this plugin in isolated environments that's something we can't guarantee or enforce, specially since (to my knowledge) `NEXUS_IQ_USERNAME` and `NEXUS_IQ_PASSWORD` are only used for the Gitlab integration (not as a standard across tools).

As always, all feedback is deeply appreciated.

**Comment by guillermo-varela** [comment]
With https://github.com/sonatype-nexus-community/scan-gradle-plugin#sensitive-data and an improved guide in https://github.com/sonatype-nexus-community/scan-gradle-plugin#how-to-use hopefully all doubts about how to use this plugin can be resolved :)
